---
- name: Install and configure Cockpit
  hosts: web-server
  become: true

  # module_defaults:
  #   ansible.builtin.service:
  #     enabled: true
  #     state: started

  tasks:
        # TASK 1
        # # 1a. Uncomment task description below and generate a task suggestion.
        # #     Note - The suggestion included Ansible best practices by using Fully Qualified Collection name.
    - name: echo hello and print it into console
      ansible.builtin.debug:
        msg: 'hello: {{ansible_hostname}} and Print out the world of Ï€ansible. See the attached
          ansible host'

    - name: run whoami linux command and print tje result into console
      ansible.builtin.command: whoami
      when: ansible_system == "Linux"
      register: user

    - name: print the user var
      ansible.builtin.debug:
        var: user.stdout

    - name: Install nginx service
      when: ansible_os_family == "RedHat"
      ansible.builtin.package:
        name: nginx
        state: present
    
    - name: Enable nginx service
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: true

    - name: Enable nginx service
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: true

    - name: Create directory /etc/nginx/certs if not present
      ansible.builtin.file:
        path: /etc/nginx/certs
        state: directory
        mode: 493

    - name: Copy files from '/root/prepared-keys' directory to '/etc/nginx/certs' directory
      ansible.posix.synchronize:
        src: /root/prepared-keys
        dest: /etc/nginx/certs
      delegate_to: "{{ inventory_hostname }}"
    

    

    - name: Backup nginx config
      community.general.archive:
        path: /etc/nginx/
        dest: /etc/nginx/nginx.conf
        format: gz
      delegate_to: "{{ inventory_hostname }}"
    





    



    # - name: Update to use ssl port 8443 in /etc/nginx/nginx.conf
    #   ansible.builtin.shell: sed -i s'/listen 80/listen 443 ssl' /etc/nginx/nginx.conf








    








    








